@startuml grafico

class Click {
    interfase y help
}
class Client {
    leer el manifiesto y proveer los datos
}
class OdooEnv {
    inteligencia de negocio
}
class Command {
    metaclase de comandos
}
class OeConfig {
    persiste la configuracion
}

class CreateGitignore
class MakedirCommand
class ExtractSourcesCommand
class CloneRepo
class PullRepo
class PullImage
class CreateNginxTemplate
class MessageOnly
class Image
class Repo

Client --o Image
Client --o Repo
Click --o OdooEnv
OdooEnv --o Command
Command -r-o Client
Command --o OeConfig

Command <|--- CreateGitignore
Command <|--- MakedirCommand
Command <|-- PullRepo
Command <|-- PullImage
Command <|--- ExtractSourcesCommand
Command <|-- CreateNginxTemplate
Command <|-- MessageOnly
Command <|--- CloneRepo

@enduml
